server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jhonathandominickdemelo@gmail.com
    password: "mfhz pyun ohrr dnem"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  thymeleaf:
    enabled: true

envio:
  email:
    remetente: jhonathandominickdemelo@gmail.com
    nomeRemetente: Dominick